package com.rule;

/**
 * Enum type to denote relation between two relations
 * 
 * @author sriee
 *
 */
public enum Relation {
	SIMILAR_TRIGGER, 
	SIMILAR_ACTION,
	SIMILAR_PRESTATE,
	CONTORARY_POSTSTATE,
	EXPLICIT_DEPENDENCY,
	IMPLICIT_DEPENDENCY,
	NEGATIVE_ACTION,
	TRIGGER_EVENT,
	CONTRARY_EXPLICIT_DEPENDENCY,
	CONTRARY_IMPLICIT_DEPENDENCY
}
