package com.rule;

public enum Relation {
	SIMILAR_TRIGGER, 
	SIMILAR_ACTION,
	SIMILAR_PRESTATE,
	CONTORARY_POSTSTATE,
	EXPLICIT_DEPENDENCY,
	IMPLICIT_DEPENDENCY,
	NEGATIVE_ACTION,
	TRIGGER_EVENT,
	CONTRARY_EXPLICIT_DEPENDENCY,
	CONTRARY_IMPLICIT_DEPENDENCY
}
